;;; dag-draw-batch-creation-test.el --- Tests for batch DAG creation API -*- lexical-binding: t -*-

;; Copyright (C) 2025

;; Author: Generated by Claude
;; Keywords: internal

;;; Commentary:

;; Tests for the batch DAG creation API (dag-draw-create-from-spec).
;; Following TDD methodology to implement the declarative graph creation feature.

;;; Code:

(require 'buttercup)
(require 'dag-draw)
(require 'dag-draw-core)

(describe "Batch DAG Creation API"
  (describe "dag-draw--plist-to-ht"
    (it "converts empty plist to empty hash table"
      (let ((ht (dag-draw--plist-to-ht '())))
        (expect (ht-p ht) :to-be-truthy)
        (expect (ht-size ht) :to-equal 0)))

    (it "converts plist with one key-value pair"
      (let ((ht (dag-draw--plist-to-ht '(:label "Test"))))
        (expect (ht-get ht :label) :to-equal "Test")))

    (it "converts plist with multiple key-value pairs"
      (let ((ht (dag-draw--plist-to-ht '(:label "Node"
                                         :ascii-marker ">> "
                                         :svg-fill "#ff0000"))))
        (expect (ht-get ht :label) :to-equal "Node")
        (expect (ht-get ht :ascii-marker) :to-equal ">> ")
        (expect (ht-get ht :svg-fill) :to-equal "#ff0000")))

    (it "handles numeric values"
      (let ((ht (dag-draw--plist-to-ht '(:weight 10 :min-length 2))))
        (expect (ht-get ht :weight) :to-equal 10)
        (expect (ht-get ht :min-length) :to-equal 2)))

    (it "handles boolean values"
      (let ((ht (dag-draw--plist-to-ht '(:ascii-highlight t :visible nil))))
        (expect (ht-get ht :ascii-highlight) :to-be t)
        (expect (ht-get ht :visible) :to-be nil))))

  (describe "dag-draw-create-from-spec"
    (describe "spec validation"
      (it "throws error when :nodes key is missing"
        (expect (dag-draw-create-from-spec
                 :edges '((a b)))
                :to-throw 'error '("Spec missing required :nodes key")))

      (it "throws error when :edges key is missing"
        (expect (dag-draw-create-from-spec
                 :nodes '((a :label "A")))
                :to-throw 'error '("Spec missing required :edges key")))

      (it "accepts empty node list"
        (let ((graph (dag-draw-create-from-spec
                      :nodes '()
                      :edges '())))
          (expect (dag-draw-node-count graph) :to-equal 0)))

      (it "accepts empty edge list"
        (let ((graph (dag-draw-create-from-spec
                      :nodes '((a :label "A"))
                      :edges '())))
          (expect (dag-draw-node-count graph) :to-equal 1)
          (expect (dag-draw-edge-count graph) :to-equal 0))))

    (describe "node validation"
      (it "throws error when node is missing :label"
        (expect (dag-draw-create-from-spec
                 :nodes '((a))
                 :edges '())
                :to-throw 'error))

      (it "throws error when node has duplicate ID"
        (expect (dag-draw-create-from-spec
                 :nodes '((a :label "First")
                          (a :label "Second"))
                 :edges '())
                :to-throw 'error))

      (it "accepts node with only :label"
        (let ((graph (dag-draw-create-from-spec
                      :nodes '((a :label "A"))
                      :edges '())))
          (expect (dag-draw-node-label (dag-draw-get-node graph 'a)) :to-equal "A")))

      (it "accepts node with visual attributes"
        (let ((graph (dag-draw-create-from-spec
                      :nodes '((a :label "A" :ascii-marker ">> "))
                      :edges '())))
          (let ((node (dag-draw-get-node graph 'a)))
            (expect (dag-draw-node-label node) :to-equal "A")
            (expect (ht-get (dag-draw-node-attributes node) :ascii-marker) :to-equal ">> ")))))

    (describe "edge validation"
      (it "throws error when edge references non-existent from-node"
        (expect (dag-draw-create-from-spec
                 :nodes '((b :label "B"))
                 :edges '((a b)))
                :to-throw 'error))

      (it "throws error when edge references non-existent to-node"
        (expect (dag-draw-create-from-spec
                 :nodes '((a :label "A"))
                 :edges '((a b)))
                :to-throw 'error))

      (it "throws error when edge is malformed (only one node)"
        (expect (dag-draw-create-from-spec
                 :nodes '((a :label "A"))
                 :edges '((a)))
                :to-throw 'error))

      (it "accepts simple edge"
        (let ((graph (dag-draw-create-from-spec
                      :nodes '((a :label "A") (b :label "B"))
                      :edges '((a b)))))
          (expect (dag-draw-edge-count graph) :to-equal 1)
          (let ((edge (car (dag-draw-get-edges-from graph 'a))))
            (expect (dag-draw-edge-from-node edge) :to-equal 'a)
            (expect (dag-draw-edge-to-node edge) :to-equal 'b))))

      (it "accepts edge with attributes"
        (let ((graph (dag-draw-create-from-spec
                      :nodes '((a :label "A") (b :label "B"))
                      :edges '((a b :weight 10 :label "test")))))
          (let ((edge (car (dag-draw-get-edges-from graph 'a))))
            (expect (ht-get (dag-draw-edge-attributes edge) :weight) :to-equal 10)
            (expect (ht-get (dag-draw-edge-attributes edge) :label) :to-equal "test")))))

    (describe "acceptance tests"
      (it "creates a simple graph from spec and renders it"
        ;; This is our acceptance test - create a simple 3-node graph,
        ;; layout it, and verify it renders correctly
        (let ((graph (dag-draw-create-from-spec
                      :nodes '((a :label "Node A")
                               (b :label "Node B")
                               (c :label "Node C"))
                      :edges '((a b)
                               (b c)))))

          ;; Verify graph was created
          (expect graph :not :to-be nil)

          ;; Verify it has 3 nodes
          (expect (dag-draw-node-count graph) :to-equal 3)

          ;; Verify it has 2 edges
          (expect (dag-draw-edge-count graph) :to-equal 2)

          ;; Verify nodes exist
          (expect (dag-draw-get-node graph 'a) :not :to-be nil)
          (expect (dag-draw-get-node graph 'b) :not :to-be nil)
          (expect (dag-draw-get-node graph 'c) :not :to-be nil)

          ;; Verify node labels
          (expect (dag-draw-node-label (dag-draw-get-node graph 'a)) :to-equal "Node A")
          (expect (dag-draw-node-label (dag-draw-get-node graph 'b)) :to-equal "Node B")
          (expect (dag-draw-node-label (dag-draw-get-node graph 'c)) :to-equal "Node C")

          ;; Verify edges
          (let ((edges-from-a (dag-draw-get-edges-from graph 'a))
                (edges-from-b (dag-draw-get-edges-from graph 'b)))
            (expect (length edges-from-a) :to-equal 1)
            (expect (dag-draw-edge-to-node (car edges-from-a)) :to-equal 'b)

            (expect (length edges-from-b) :to-equal 1)
            (expect (dag-draw-edge-to-node (car edges-from-b)) :to-equal 'c))

          ;; Verify it can be laid out and rendered
          (dag-draw-layout-graph graph)
          (let ((ascii-output (dag-draw-render-graph graph 'ascii)))
            (expect ascii-output :not :to-be nil)
            (expect (stringp ascii-output) :to-be-truthy)
            (expect ascii-output :to-match "Node A")
            (expect ascii-output :to-match "Node B")
            (expect ascii-output :to-match "Node C")))))))

(provide 'dag-draw-batch-creation-test)
;;; dag-draw-batch-creation-test.el ends here
