;;; dag-draw.el-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dag-draw.el

(autoload 'dag-draw-create-graph "dag-draw" "\
Create a new empty directed graph with optional ATTRIBUTES.

(fn &optional ATTRIBUTES)")
(autoload 'dag-draw-add-node "dag-draw" "\
Add a node with NODE-ID to GRAPH with optional LABEL and ATTRIBUTES.
Auto-sizes the node based on label length using 2 rows × 20 characters constraint.

(fn GRAPH NODE-ID &optional LABEL ATTRIBUTES)")
(autoload 'dag-draw-add-edge "dag-draw" "\
Add an edge from FROM-NODE to TO-NODE in GRAPH.
Optional WEIGHT, LABEL, and ATTRIBUTES can be specified.

(fn GRAPH FROM-NODE TO-NODE &optional WEIGHT LABEL ATTRIBUTES)")
(autoload 'dag-draw-layout-graph "dag-draw" "\
Apply the GKNV layout algorithm to GRAPH.
This performs all four passes: ranking, ordering, positioning, and spline generation.

(fn GRAPH)")
(autoload 'dag-draw-render-graph "dag-draw" "\
Render GRAPH in the specified FORMAT (default: `dag-draw-default-output-format').
Returns a string representation of the rendered graph.

(fn GRAPH &optional FORMAT)")
(register-definition-prefixes "dag-draw" '("dag-draw-"))


;;; Generated autoloads from dag-draw-algorithms.el

(register-definition-prefixes "dag-draw-algorithms" '("dag-draw-"))


;;; Generated autoloads from dag-draw-ascii-edges.el

(register-definition-prefixes "dag-draw-ascii-edges" '("dag-draw--"))


;;; Generated autoloads from dag-draw-ascii-grid.el

(register-definition-prefixes "dag-draw-ascii-grid" '("dag-draw-"))


;;; Generated autoloads from dag-draw-ascii-nodes.el

(register-definition-prefixes "dag-draw-ascii-nodes" '("dag-draw--"))


;;; Generated autoloads from dag-draw-core.el

(register-definition-prefixes "dag-draw-core" '("dag-draw-"))


;;; Generated autoloads from dag-draw-dot.el

(register-definition-prefixes "dag-draw-dot" '("dag-draw-"))


;;; Generated autoloads from dag-draw-optimization.el

(register-definition-prefixes "dag-draw-optimization" '("dag-draw--"))


;;; Generated autoloads from dag-draw-order.el

(register-definition-prefixes "dag-draw-order" '("dag-draw-"))


;;; Generated autoloads from dag-draw-order-simple.el

(register-definition-prefixes "dag-draw-order-simple" '("dag-draw-"))


;;; Generated autoloads from dag-draw-org-validation.el

(register-definition-prefixes "dag-draw-org-validation" '("dag-draw-org-"))


;;; Generated autoloads from dag-draw-ports.el

(register-definition-prefixes "dag-draw-ports" '("dag-draw--"))


;;; Generated autoloads from dag-draw-position.el

(register-definition-prefixes "dag-draw-position" '("dag-draw-"))


;;; Generated autoloads from dag-draw-rank.el

(register-definition-prefixes "dag-draw-rank" '("dag-draw-"))


;;; Generated autoloads from dag-draw-render.el

(register-definition-prefixes "dag-draw-render" '("dag-draw-"))


;;; Generated autoloads from dag-draw-splines.el

(register-definition-prefixes "dag-draw-splines" '("dag-draw-"))


;;; Generated autoloads from dag-draw-svg.el

(register-definition-prefixes "dag-draw-svg" '("dag-draw-"))


;;; Generated autoloads from test-research-final.el

(register-definition-prefixes "test-research-final" '("test-research-node-final"))

;;; End of scraped data

(provide 'dag-draw.el-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dag-draw.el-autoloads.el ends here
